
services:

  # mongo:
  #   image: mongo:latest
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - ./mongo_data:/data/db
  #   env_file:
  #     - ./Backend/.env

  # postgres:
  #   image: postgres:16
  #   container_name: mypg
  #   # restart: always
  #   environment:
  #     POSTGRES_USER: myuser
  #     POSTGRES_PASSWORD: mypassword
  #     POSTGRES_DB: mydatabase
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  postgis:
    image: postgis/postgis:16-3.4
    container_name: pg-postgis
    # restart: always
    ports:
      - "5433:5433"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgris-test-1
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:

